Src/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>Custom objects for students</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Src/objects/Student__c/fields/Nick_Name__c.field-meta.xml
<CustomField>
    <fullName>Nick_Name__c</fullName>
    <label>Nick Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Src/objects/Student__c/fields/Roll_Number__c.field-meta.xml
<CustomField>
    <fullName>Roll_Number__c</fullName>
    <businessOwnerUser>abhishek.girhare@fexle.com.training.staging</businessOwnerUser>
    <label>Roll Number</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

Src/objects/Student__c/fields/Student_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Student_Phone_Number__c</fullName>
    <inlineHelpText>Enter student Mobile Number</inlineHelpText>
    <label>Student Phone Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

Src/objects/Student__c/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <description>Student Details</description>
    <label>Student</label>
</RecordType>

Src/classes/StudentDebug.cls
public class StudentDebug {
    public StudentDebug(){
        Student__c s1 = [Select Id, Name, Student_Email__c From Student__c order by createdDate DESC Limit 1];
        system.debug('Check Student Data' + s1);
        
        List<student__c> StudentList = [Select Id, Roll_Number__c, Student_Email__c, Student_Phone_Number__c, Nick_Name__c From Student__c order by createdDate DESC Limit 5];
        system.debug('Check Student Data' + StudentList);
    }

}