Src/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>Custom objects for students</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Src/objects/Student__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>10</length>
    <maskChar>X</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

Src/objects/Student__c/fields/College_Fees__c.field-meta.xml
<CustomField>
    <fullName>College_Fees__c</fullName>
    <label>College Fees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Src/objects/Student__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Src/objects/Student__c/fields/Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Date_and_Time__c</fullName>
    <description>Student records filled Date and Time</description>
    <label>Date and Time</label>
    <type>DateTime</type>
</CustomField>

Src/objects/Student__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <description>Student Date of birth</description>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

Src/objects/Student__c/fields/Exame_fees__c.field-meta.xml
<CustomField>
    <fullName>Exame_fees__c</fullName>
    <label>Exame fees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Src/objects/Student__c/fields/Indian_Student__c.field-meta.xml
<CustomField>
    <fullName>Indian_Student__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Indian Student</label>
    <type>Checkbox</type>
</CustomField>

Src/objects/Student__c/fields/Nick_Name__c.field-meta.xml
<CustomField>
    <fullName>Nick_Name__c</fullName>
    <label>Nick Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Src/objects/Student__c/fields/PG_percentage__c.field-meta.xml
<CustomField>
    <fullName>PG_percentage__c</fullName>
    <label>PG percentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

Src/objects/Student__c/fields/Roll_Number__c.field-meta.xml
<CustomField>
    <fullName>Roll_Number__c</fullName>
    <businessOwnerUser>abhishek.girhare@fexle.com.training.staging</businessOwnerUser>
    <label>Roll Number</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

Src/objects/Student__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Madhya Pradesh</fullName>
                <default>true</default>
                <label>Madhya Pradesh</label>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Uttar Pradesh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Src/objects/Student__c/fields/Student_Details__c.field-meta.xml
<CustomField>
    <fullName>Student_Details__c</fullName>
    <label>Student Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

Src/objects/Student__c/fields/Student_linkdin_Id__c.field-meta.xml
<CustomField>
    <fullName>Student_linkdin_Id__c</fullName>
    <label>Student linkdin Id</label>
    <type>Url</type>
</CustomField>

Src/objects/Student__c/fields/Student_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Student_Phone_Number__c</fullName>
    <inlineHelpText>Enter student Mobile Number</inlineHelpText>
    <label>Student Phone Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

Src/objects/Student__c/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <description>Student Details</description>
    <label>Student</label>
</RecordType>

Src/classes/StudentInfo.cls
public class StudentInfo {
        public static void InfoStudent(){
        Student__c s1 = new Student__c();
        s1.Name = 'Ayush';
        s1.Nick_Name__c = 'Ayush';
        s1.Date_of_Birth__c = Date.newInstance(2022, 06, 07) ;
        s1.Date_and_Time__c = DateTime.newInstanceGmt(2022, 06, 07, 17, 20, 32);
        s1.Student_Phone_Number__c = '9893030346' ;
        s1.Student_Email__c = 'ayush@gmail.com';
        s1.Student_linkdin_Id__c = 'https://www.youtube.com/' ;
        s1.Roll_Number__c = 170260420;
        s1.City__c = 'Bhopal';
        s1.Address__c = 'Bhopal';
        s1.Student_Details__c = 'college Student';
        s1.Time__c = Time.newInstance(17, 17, 17, 17);
        s1.Exame_fees__c  = 2000;
        s1.College_Fees__c = 40000;
        s1.PG_percentage__c = 90;
        s1.Country__c = 'India';
        s1.State__c = 'Madhya Pradesh' ;
        s1.Indian_Student__c = true;
        s1.Bank_Account_Number__c = '7894563217';
        insert s1;
        
    }

}